### ISSUE TITLE
Create custom Docker image to avoid installing packages in every CI job

### ISSUE THREAD

**Issue by maxkratz** [maxkratz/matrix-synapse-saml-mapper#2]
Todo: Create custom Docker image with all requirements preinstalled to reduce CI runtime.

```
steps:
- name: lint
  image: python:3.6
  commands:
  - &setup pip install -r requirements.txt
```
